language: node_js
install:
  - yarn
node_js:
  - "16"
addons:
  chrome: stable
sudo: required
services:
  - xvfb
before_script:
  - "sudo chown root /tmp"
  - "sudo apt-get install chromium-browser"
  - export CHROME_BIN=/tmp
  - export DISPLAY=:99.0