language: node_js
install:
  - yarn
node_js:
  - "16"
addons:
  chrome: stable
sudo: required
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start