# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.9.0
  browser-tools: circleci/browser-tools@1.2.3

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      example-job:
        docker:
          # replace with your preferred image
          - image: cimg/base:stable
        steps:
          - browser-tools/install-chrome:
              replace-existing: true
      node-test:
        pkg-manager: yarn
          run-command: yarn test
